<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class AlterStockQuantityTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $products = DB::table('produtos')->get();

        $values = [];
        foreach ($products as $product) {
            $values[] = [
                'stock_id'    => 1,
                'produto_sku' => $product->sku,
                'quantity'    => $product->estoque
            ];
        }

        DB::table('product_stock')->insert($values);

        Schema::table('produtos', function ($table) {
            $table->dropColumn(['estoque']);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('produtos', function ($table) {
            $table->integer('estoque')->default(0)->after('unidade');
        });
    }
}
