<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateProductStocksTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('product_stocks', function (Blueprint $table) {
            $table->increments('id');
            $table->string('stock_slug', 100)->default('default');
            $table->unsignedInteger('product_sku');
            $table->integer('quantity')->default(0);
			$table->timestamps();

            $table
                ->foreign('product_sku', 'StockProductSku')
                ->references('sku')
                ->on('produtos')
                ->onDelete('CASCADE')
                ->onUpdate('CASCADE');

            $table
                ->foreign('stock_slug', 'ProductStockStockSlug')
                ->references('slug')
                ->on('stocks')
                ->onDelete('CASCADE')
                ->onUpdate('CASCADE');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('product_stocks');
    }
}
