<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateStocksTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('stocks', function (Blueprint $table) {
            $table->string('slug', 100);
            $table->string('title', 100);
            $table->boolean('include')->default(false);
            $table->integer('priority')->nullable();
            $table->primary('slug');
        });

        DB::table('stocks')->insert([
            'slug'     => 'default',
            'title'    => 'Estoque físico',
            'priority' => 0,
            'include'  => 1,
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('stocks');
    }
}
