<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateMagentoCategoriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('magento_categories', function (Blueprint $table) {
            $table->unsignedInteger('id');
            $table->unsignedInteger('magento_category_id')->nullable();
            $table->string('name', 255);

            $table->primary('id');

            $table
                ->foreign('magento_category_id', 'ParentCategory')
                ->references('id')
                ->on('magento_categories')
                ->onDelete('SET NULL')
                ->onUpdate('CASCADE');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('magento_categories');
    }
}
